defaults: &defaults
  FACEBOOK_KEY:
    'CAAH7RVYBZCM4BABhnrNXRJIzz7qO1KVngW69cjlkWxVR7OTEZBMS6B15yuhcpl37rxm8GtZBAOxKFjTrmBfo89blQWpFPuZCWtUuaaZBAr06S2ZAEUvyZAIRytBrxlP5lYhg5SZAcLkijPnCgjqHBNTZA3uHr8E5cUKlGZAaHZCJPAzwrH5PQwdGAnCGZBHTnzfZA6ZADtPD7CdcF2yoNHERqksWvR'
  TWITTER_CONKEY:
    'kOBgaCJbs95WROUfAaUYvKAB0'
  TWITTER_CONSEC:
    'URQKvxdHZeONEU899rvWZjYyFzg0RcW1HDZxUPYJ7Z6tccIcmL'
  TWITTER_ACCESS:
    '34336803-nwI8nRSjgfPFa9ui6u4kWsFMofN8ndqe5KfBqMOUL'
  TWITTER_SEC:
    'YnmsFBuOC08RsJwomylsaoT6XsXTjIf4fOb2pEQkR1VX6'
  MEETUP_API:
    '6f67646757f695b2da311dbb4065'
  MEETUP_MEMBERID:
    '1427021'

development:
  <<: *defaults

test:
  <<: *defaults

dev:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
